### PR TITLE
Math magicians: full website

### PR DESCRIPTION
**Pull request by MarcoOquendoC**
# [Math magicians: full website](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_full_website.md)

## Hi good reviewer,

Patricio greeting

### Project requirements

- Create a website consisting of 3 pages: Home, Calculator, and Quote.
- Match the layout with the given wireframes
- Add styles.
- Create a route for every page.
- Add navigation links for all 3 routes, and display them on each page.
- Use React Router.

### CODE REVIEW

**Review by topeogunleye — COMMENTED** [review]
Hi @MarcoOquendoC, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project that has failing linters, Kindly make sure your linters are all passing before submitting the PR.

## Stlylint AutoFix
- [ ] if you have a lot of CSS line errors, I kindly suggest you fix them with `npx stylelint --fix "**/*.{css,scss}"`, however, get used to fixing the errors line by line also because it'll help you learn best practices.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by MarcoOquendoC** [comment]
Hi @topeogunleye,

I missed that linter thank you.
This PR is from feature/hooks to develop. I don't understand the "Gitflow Not Used" warning. Kindly be more specific.

**Comment by topeogunleye** [comment]
> Hi @topeogunleye,
> 
> I missed that linter thank you. This PR is from feature/hooks to develop. I don't understand the "Gitflow Not Used" warning. Kindly be more specific.

@MarcoOquendoC . Please ignore and submit again. That was a mistake

**Review by elisha2kyakpo1 — APPROVED** [review]
Hi 👋 @MarcoOquendoC, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The PR title and description looks professional✔️
- No linter errors✔️
- You have a descriptive readme file✔️
- Descriptive commit messages✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
